import localFont from "next/font/local"
import "./globals.css"
import Link from "next/link"
import LoginBtn from "./loginBtn"
import LogoutBtn from "./logoutBtn"
import { authOptions } from "@/pages/api/auth/[...nextauth].js"
import { getServerSession } from "next-auth"
import Providers from "./SessionProvider"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="font-sans antialiased bg-white">
        <Providers session={session}>
          <nav className="flex justify-between items-center p-4 bg-gray-200 shadow-md">
            <div className="flex space-x-4">
              <Link href="/" className="font-semibold hover:text-blue-600">Home</Link>
              <Link href="/list" className="font-semibold hover:text-blue-600">List</Link>
            </div>
            <div className="text-right w-full">
                {
                  session 
                    ? <span>안녕하세요 {session.user.name}님! <LogoutBtn/></span>
                    : <LoginBtn />
                }
            </div>
          </nav>
          <main className="p-6 max-w-4xl mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
